local AssetID = "rbxassetid://12187365977"

local Rubik = {
    Thin = Font.new(AssetID, Enum.FontWeight.Thin),
    ExtraLight = Font.new(AssetID, Enum.FontWeight.ExtraLight),
    Light = Font.new(AssetID, Enum.FontWeight.Light),
    Regular = Font.new(AssetID, Enum.FontWeight.Regular),
    Medium = Font.new(AssetID, Enum.FontWeight.Medium),
    SemiBold = Font.new(AssetID, Enum.FontWeight.SemiBold),
    Bold = Font.new(AssetID, Enum.FontWeight.Bold),
    ExtraBold = Font.new(AssetID, Enum.FontWeight.ExtraBold),
}

return Rubik